Adding capacity to summarize microposts as well.
jnjosh/internet-weblog pull request #10
Opened 2018-10-27 20:35 UTC by ghlecl

I have some micro posts that aren't as "micro" as they should be.  Two or three paragraphs.  Because of that, I would like to summarize them in the main entries list.

Still, I like that the color is different for microposts, as that is a nice hint to the reader (for instance, that this one can be read in 1 minute!).

So I created a new option which, as I've done in the past, is optional and defaults to the old behavior.  Hope this is acceptable.  Don't hesitate to comment.  :-)

2018-11-15 15:29 UTC, jnjosh requested changes
This looks fine, I just ask that you better document the feature in the README. The `SummarizeMicroposts` section still talks about grouping.

2018-11-15 15:29 UTC, jnjosh commented on README.md
> +| `[params]` - `SummarizeMicroposts` | `true` or `false` | No. If true, Microposts will have a page with a yearly grouping just like the posts.  If not present or false, the default of not summarizin
Would you mind better documenting this feature? This appears to be copy pasted and you updated part of the sentence, but not all.

2018-11-15 15:43 UTC, ghlecl commented
Just did that and pushed to my branch.  From what I read, I think this is all that's needed and the pull request picks up the new commits.  I guess it shows I don't do pull requests often.

2018-11-16 17:16 UTC, jnjosh approved these changes

2018-11-16 17:16 UTC, merged